
from memes import lcs_dynamic 
from memes import lcs_divide_conquer 
import time
import matplotlib.pyplot as plt

def time_collector():

    strings = [["R9s8GyV6tJ42wMqQ7EoKjDZ3c1hH5xX0fPnBmUaIvLz4YbArFk", "xP4m7vYhD0J9zN5L8tWg6BfQ3eA1jSlE2oUqKwM_RiXpCnVbHc"],
               ["uzxjkgnecijjbgnkgmlfsygyqvokheiefhalsdxcouamrekhncmyxovybsnn", "jfpyzbsbsrskhjrmrqckbipisfvkvlyozomzmkrqkbmcjpcxzysmdcctyntv"],
               ["epwogmmgwpqiekeevvgaqpdvbdyfcqtkfxwlvrghuczyavjaupkqpiibgecngjcoojrkdw", "vlfqszcepqduhrzxwrijqddlyuxbxdvpoefpaajyoyfcdfypqyknpchtypbkleczqcurdl"],
               ["irbdyyuboskbwznuqujmhuncckbnelvwacsstsbgsnzzsiorhqhgufejgahsekptugpcbhjqayiduhrg", "nfqhzrciqnihkwvmrvogdahpnslfsfytbmgsdyrlrhxdhuausorgzzkrtjnuopzxrvpswctdsouimlqv"],
               ["xdhaiqujjjxnyjfinntdvblkobfpzjjawtjhuzhnhorojysslogajlveoytmqlxxjhittdrbfycmcldhnqcnxbhdaf", "xfaooyufqmbpmudoxflhrgofaqvuulvyphnzwwzdlczyudiozxlvzfrynntiroumczwtbwdpepxbsvmmumpkkmebyd"],
               ["fwwbprophdnzdjupjzfqhifbecdwtktwrbcguzbncsfjatueszoxqdcrltyswxrzllktcnhslluhaoxgidskdiiwjabbmocuqbxt", "obdlnzqyynuwnvyapsljurqthkesweipnoavfhgzconuvypoeaeacxitrpuekpzkdpqqxvdqiwklnajnmzqlrfakclmxuzzmdxqr"],
               ["lknkwmjwnprexqevlcjcyscitsbvqtgyvyzrgpqgmdzbdgspajxwmegwqtkqsjpaxzczroyyxanmuwvjzvjvgecynsjscynkxmtyskcgspvgja", "wreunbndqkihqfobwrwsdmqjepoivdyposgmavhoapnrphbuptckrxvpqiivhsolbonofzlzibdarhieyxjbrwdfwmluyuvxtibodyrrwgjxuv"],
               ["vrmjaqbowbmztdexdagpefedixovlhfdsbedfetgkfvvjzpwzpnnmfizalargdowtylpqhrcrwetmxlcfovpnkxbdycaxmaxexskzsbakjtwduuqewrmrcee", "dqefkapnldhlhvsjerbevjgiypqosofdxmyumccsgcsrzarijdntrqvhhjljtbxijvhsiajcuczzxlgujrtkuwkexnqvvqtnfqxaanfntnhsdioyduvbmmiw"],
               ["tszcmtyeesrqppocfndzlpfbgxcwiisbairzkifcnvcprgxeidaavjumqamtqplffecffojtgpbmdlbezabtfehbpbgmgbcyryraexjkemxufwwtsjkoqynsqzaxhdbhbe", "rtkvaxzpuvnrklanxchmtvnticdocppbfntmlxuzqsgbilpqjdzbrpozhgwszwfewsucaidizodamzuzcgpbucinvvoymielmvnnccbvpspgpwkbjfhrthcvuhnbrrxbmx"],
               ["ygnvoznlsifanwgxowlqsgxfwudwrtfubddmhmyvitllhpzqqitmpdnwxxiqrplvsduxzogtzdfikpgxgrnfzlyskathwpqmjaamksorhykgsjcuhtbuhsafbqyrzzuvjotsfvlvszfb", "albhixoztouonpsdcgajccgjytxhmremihjjdbkhyyaofhqswzhuavjxdfmwpehdrdnqkraqylfaxqezfznxhkfydtrvlfeydxmjqgzqzbfzxjrfdfmkymgpmgeuacxpvodzhelsfois"],
               ["flkwjcksebysueemizusdgiuoobdgrqnbhfhjwuoqxqpazqmxshqlegubxqageigpmetynpxngoxaanluphdmjlcgywdameobbhfbfqoonquejmqznvvieorcndhdycsydtaohrmasyimrgqzbeduw", "ohynzvolphvcxjfnuyujbulitdcxfjqqpatkzolsvumtdezlolecpmhghfejnsrhghmybgqoluufcqvidbjicjgkmubpwlbmpdfgkoixhhxfufpafxvruqzkpajddpbufbvwgzsspdkjdrmulzyjxv"],
               ["fhcdulvogcizheljfkaitmqzyujfwhbvbilgopqjpsfnaoeitruzkrurdoyzovbvqfzqtsygzoewjtcarafibtbhptmfgsaqdrpqrmlkzpxujkrrzifubihosnbgubybxepikutwzhsrfcaryggceoapkknzrwyj", "fzcpvlxzyxmrqxpikjfobsvjxctnbvzcinrqfwismbnkedwtrmudtohpcvinuacqpnfajoqdvdejjvtzkgarxwgtitcsnbzzbhbfojsapnrftynjxwakmhbrboyaqtphxfhohipiiycmppkbktcbwbwkfnqsqnit"],
               ["gyhohztbwolzyigznojhfznnjegocftotpdcyiyhxsbmxcqlnsodpdpurdfjhatdvsjivwqfcxnpyerlyffdcjdoujzfylmzhjtzlsqnlibomqgyoaeveoqcxovqnadpceyhkyvpegjoaccykmdhcmphmexfxsfastlymeumzp", "ydiyamoblhhwjwxosbqbsdbbvjusyhmpobvsioaktnviszelkxdwvzpdbogebkewsndjybcanitufniobortqgyewhrqoikaiyjorjsnnqnovceugkdbpnvzwwqsppfhbftbzcgjvjzorrpmykdplazuawtlrbzcdumrmgodwu"],
               ["rccwtaoohtttwkjppssoffjzcticoxuzcdmlzpbxcpsqzclvswxekroomjxzmjvgdcjgdxybxpxipifmriymmjnalkcsmibcrdnxvrmvhvldfxiknszjcaclzyjrnkcpncjjkygewnqgwiainqrqckxwaaagyoobfqolysxfdnhebmkflmdu", "seltpnofuzddsvjrwsakqjnlwgyitoyubtforoqwfoqkawaypjtpryktrnhkjzcucpwprfymwmbvitctpzxgiziwhlphgdfyyrcsrioljnicfobnvojiwmkgcsuoedskxvvdxjzkgehboqdigvtfzszgjnwgbpbuikxnahsqvccsvdwrdasl"],
               ["ezwxcsdzqrkhxqsgdfbabyvnowvhzxcvzilgsmdmzuftzqsqxqejzdrjoobonzybewvajampnnewwlcnpaxoletwwrofoysawmorwhvkasshecwmtlloapohxkglorvzoggvbblytypppekduhwfjmkjthctssmabcalifgrimidcjgidqupxvgxvfhapq", "ipsbdbzkxstfkpfvztwccapnbrdybcxgylneynuhrqjjpzdzlxphamzcslsikmrmqqzvtwebuqcregugntjwewtkqggyfeilbpmprlnktelwasfdsmjaejavpuaszxwcsmjfjkibxmvvcgwmtxfgugcxupxrlryxkprttkcbntbgxtsjqyrfscaapifzze"],
               ["tfaklanakkeutbhbgepvdtoaiwxjinomwbijbbcrqjovtiupznhdnfhasjibvibpvuhclxoaefpfuvucolzhrkbsiiavhdcotlbgzdflobbpgxqczlpcjmmoadnjgwbrvjkbdobfyheyetpjhilmclonjpejfgpaiwqinluwfskngxvwejjhermgsivdgiovnpkurixd", "migpnnhdofdjefvuqlxmjnofxeizqplxkwqvikqoornnmanahocrrclptnobgiyazjifecsgktiqbxttfforrhabibxpkiqlxajcvqnidjqkdkjvnmitypnmcjtggfojcxvckfuakrjbptsmsxikuseybpgdbusynmoltmfganzdwxyivxjjavkjltjvkhikpmxuilys"],
               ["wunicvdgowagcyivlgwcabzkvkwtpofbkdrpfaephhiafzvmdakenjytaantvkvcxfgouwzqtveydtpyfjfccypblulukrdgtiyhjiqkmdeyfsgatvkssmcbalcvdwwwbadrwvuygpsdhcnupxndjdgsndehosnxjjitkdydhzreqobcujodujnlahftacmwyfftuyzskohwurmrfq", "qwexsjsqwgfotrcwfbqktmmibjswijlaiodfijsxhrephkzjtsgeqctzddqzpuhtwnrpvgqwkoqcbbrqgvsbkoepafcyymdadebtijkglqnsmqhcxqxninsadhemvvheamavhrbnjkahryysrxoqgspfjlhyxgdswrhalqqrhrpdwhjqouyaexhwubhrhqizdzoosyjptwycoffnuq"],
               ["ljmqjxjhsapuncmmagimxgkdboloqpataevplrdubljrczxsefnbrdcqiybcaewsphmlomciqnlyqrzoebnbmowenqcgghqxgrtaowuwirbmboyqnpspgjznyrugvqviprvcfdaoakexdlhltxjaurlmqadelbdifdomlkywrnpcspnciktyamxwqceqplryeiacnhujqwmalskglwpoalxuxmvz", "dullbmxvhzjidznylrirfpocckvjxmwfpcowgbhuilhgnwnlcxcweeyfzbhirxfbiehosecystickiwkftzydryjgqpsdbvjfmdttmhbkpwfiekjrxqlabumhkgmalmngryrfiasyyxvcosefmajiapfwkknetreuoyxzslpdfokzkwmnyuxknrhjdowuupsmulfyondpeabjeuplhskabnhcqsd"],
               ["oqikyxqwofabslaaerapievtqetaheuszgvsjrydaakpvxzikivnzjhbzcxawtqhlqwvmuwvqgjtpcbwahuverfydsyzkbmdizqkmnotznpnuulymrftjqbcfckkkhyrzqqdnwovxhowgwmptwjwkmiolxhzpileuhfyioegsqxksshzptnesqtgmzjmcnlwjxmhjudgnhhlkzpchiebkiwsznyndkihhkkwxz", "hiqnvrgzqlpzirbvjdnxcgdahbibfpjsuufzsgerimlpyxiegcjqrqcspgfanqozkkxeptopyenieyynsrwckzmtwtiosrqdaswtecbgatujdsuzznpvaxuiakewilduyoxsmjdwdpbtmgkixqfzcvwadtqlbjvszsojpeuwxenunwertzngqqstsatwxvvmcuizpikwlscrpinogttkvnskxnbbttnckbwcda"],
               ["drdgxeglzmcaazfayhhnhbwarovalcbwsuvulotjinkuqznkskrocgfhkdntpundkdownjdfuovvyzudczetktgcdglhusabpoozskeoynzyjuqhrruixqxtxksmkwpuwduwmopjbckqkdowrjakhnsarisciquwvpwuxqqzqtdevabvoriaozaixxcvkuuievzscdfpqylybynvdcpcyjzmmsudbkhdbfkoejchrqbrsneg", "civtqqgptntwiergdtpnznpxnglcwgmodndgytigswuybwegynwaizudpapykchxjcockboxvfkbucpqkawlcgmttryojbzugfxtqrkgngfhutpddxtlbzupkmatidonxxighevrboyhpggbxgngdcqpulvfuiouqmbtrvrqzmdhpanakcayosriqeyiucqacrinplvhxygwkmhgxnrzobbzcsqxfrqvdmzfhmyzhgohwjrg"],
               ["fcqzlvizqiiutjjqugofodiygvdzaouvdhyzsxvamihhyllgrnakraobwswvwoxdrtlqnbydpbdccxuqrbxoycgzkrgfnerpihffszbzdwsbswrvnmitmgltwfjgntqatslzglmlcdgkdyrxnlpazmphzxqybqgwipvstksnajhtbdswgndcvbatzhxixuovzzyltrxfmxvqahwtozqnrhyrsfeuelvehlargfbxwaxmzzchlsblautzcn", "opuvhtwbhodnytwqkzqsrmhhwoaenfandlnzqveenyjqjvotjukqgxztyjwfzhvgptaoziznkzeedatqdyvjqwjqewzlepfzdpwbphczkasvniryztznfepngdtcjxqdfupocqubyuqnhoznwgkxdagpmmclzculhmlepuonwsvqdplsofjnpqlteuvdtqwpjpbwumyfqmlpgveobzrmtbirgcxvkrtqcsexstthxhgoppwhvoiylhorsb"],
               ["utjdphfiwhlsecmaojzotgnpiuhwvugsplhujxnjyqobwvsmyraarqtiepzfelrtbcuxvvywvqygqmgjkaaoqqvavlwvadylfngcyrhmoqhpnocfoupvxtqzmudfowqzfmdpauaxayzlffjzsfqazitcfwnygkgqechnktdqxwsnwcruxnvswvkmlenyolyimxkpsbjgdazcapdwkjwjdsmswloobhdjakdmhpmqzuzgfrtpeqmkaoxfzvlarxzutkfj", "lttxxcwxomumsqafyskwppashjidpelnjhgcmhmkgtxmzcqshndbppyvforjmlpzyydxlqiicxtaczqjxbkswovbotwnsjvhafenltbqoswckyxpgjgyvnpkxtxhyrnimzubzlcmojeavsbryazbawgrewvxjxbcwzcsyatqusjnbyazvryyazdkrhfozveylwhmdbzcbwyreljivrcrydtvxweqolaltvvublubiopskrkyiitumjioxniuermvzlqn"],
               ["ltkisgwnnyesoobveyfubxzzijwzlccbxfbwudmdfntfdwzpbjugmootzlywmchwpqfklhlvtxohjsgdqkjasgzdhfturtxwmzcrczpybyuzjbhvdaejnfczfkmhxclvicinzgapzwoltmyhiwonalxdcfdmizcsdfhcrwqasojvspqioiyrffihqsrcjogqxtgvpcxhekchsgkjpjcgcficmczeuhafxsnlxiwwxmqafpgdfshdbqonoaimyovhtuzobiatebcbtq", "mihjmkmpphgijlphvpfrapnuodonndviwrqhdexnlvavnemlcuminqcvptjbsyhobkzqdkiuibjwdmfrmonvwxmoespgwxspydhtawksuqrcmqozvzvwlzdjowlydfbjwyqxflcibipbgpvoyqhgsmhigojwcqbceoariozdfuramxdovrnwpugbbkxmjmsnpeseheemhmbntqhqmftthptqgkramlcnuiaziuixagitnevskwakbpvcmmgtkovzflasxshjizxoac"],
               ["haqyzliwtpjizfrhkicwrecqzhjpuadjsyjaokmowhgwvwipinmfmthyibhwzlbssjziscajjiuyxsgtucxjrxftmiodlsrbjsbhmfyrutuayarswybiduixpcwibkdolvxkxulwodymuktayczookkyhvvtjxhlclxvzyeilrfkgxgtvnntogmogjxcyhhmnzkzdphzqagsrrqtdctesntxzvmqltnvjvhedqfhxwcopmkzanfzohalckfplrnikrwlldvmbkvmjibtakncxqzw", "zpmikvhpczhltdxupnfjdjnbrqsqhoztgyqysgzfwbwiuvtaomfegejintsuqvlqyqummxoaeagcqmbgxnumqzgdrfiojychfuakpvybpjavpgcmclgdkbqjhzcccpgtsjhomcuemyrminzavhfdlocfngmxihcrhnvkdedirpcllgdncluvgfwradpxqwczooqfxfgmzuoolvoxzwaazobemhmjlguqhcsjgbrtyxkngmquexqzyzukwsiogkllnsndupwlowchqfcfsryeyucn"],
               ["jnsngljyfumilmmxxdcazsjcbiwrrpvdqrxgrzotpsnavutwqtockvntcmytywqxmvywwewjnkrqeirlafphzifxbmsjfdrbqlemujnrouqrbuellyiuxsdmmgrmslmjhycbgfesdrazkjoqpwdysaexxlebvocrsankcbaxppjhvszaqrganpiuaehtujhlqijpblqaekmsmlflojgipslhuugnovyeuwhmlioueldublszsbvixoyrylmwymqozfufvihquneeqplfyldhaodyozrpniwflm", "vulxmgmhqgbcyqundddyaegruvknpcbiatyfffwaicicixvwgrrmanaclflvqvxezbeezxrncpzhxpoqptlzmnlffspnnjfmeumclmlqowkxzmgvepuiyryitnhiakqikjveitmaelfunoeunfsvuqnfdwsxaxltnubycurixnrpqslthfrhlndfbidimsqpjkogxdiaidqmfbfsiqavyaibbiykdiquvtdrwsnutiqdnloqmskqmwabqimlottsslrifjplzgjhlrvcetnbdutdonllykosor"],
               ["jmnmjmpcvrvjnmrcktpqyluvyyltjjmecjbftecivkgkveukbkbxtgzdhqbwtecieirwkjometesuqpbrnuvsdbsxgeklkxnwmgziknlwrfhvfhkovcvairodksunlkkmnxtzfyswfoublnznmycwlgktfssfkzolyedupcqggwairhtcnjmildcjheagtfjhrsgwxiekfrjznucwyhnfadrnuyfapazhenwcqblqwsponyiduwerybwfvmmizfrsqeewhkzuxcpyciwtoudvxkkfbhiqidnrhqwuunwzjei", "scjeophxaslobutjoxbzglzuftuzsfhiiihafttddtyojtkkclzxrpyxqusnuhmzktlietwneyvsdlokbnxrfqasjfglfsgodmybguynwpvezphvfwdnbtcwyrhkvywbgmrfqgnvgdarolqzbiplqfpbapiuwovuwfslhmgrwnzvitdotprwzdezwjnjsubtzhlpqpezufooaqaawnnrbzpduleiusyfvolixsybpulywbgbtrqsgripzmodxldwfrjqqrbsihieybeevgxsibzydkvdkcpzicvwqdqghxpb"],
               ["orkjcrnynxvddikbovcqnswybbmnjjykljzneasyjkakcttwgqpmewstxsqihepjpczbqnrrqmezgtpsrkgvtlersujucvunfllvbfptxvkrkdlxreyrxxazzlrjmywjxfxvibpjvulhpowfageokjzdnjdynxfzwulhygpkikhgurfazwreltgjnqqymfaniwwhboytwrufqeytjohmoiohbalmhxjvkzxxmlmgeanaprdpshxvixiqdwvlzpsayeqfscvseibawxmhaueiaxmfnpcttliurcpdywunzkajtkldqjtdqo", "jjywbrczwcklkptgjounkixvpeqlizjtuadaipahehcfpjafsnkxzhpvjmuqzvmkmpwcvhnibqqatlhbohlqtgxvboytybfugpkscofeahuvuncyvosamogzxwexeunckddbhslsxqqrcbltxmimswobamwytnzeybirmasaeolkiwkpmedxdccduwwjgfkjxyvikljqlcbvrxdafmkomprgmjiqjemduathuhhrxspizxgstihxcgoelxtxflnlopooechzxajwsdrumaxrcmwnwgdlflvzqytzrtefcysuftiwpuqdck"],
               ["iwbrnjutldsdbjjbwumnnkqudeulusfqosuyzcrykntsoagaclhqgpucotbwjlzdevpzwmklttiuzbtxjlnguxfpaqecqlmbztaqetalxxgawubmuexwcokzotpcathtmbferfypyfbmnqsnsslexyqptsvohlshaoovwlevhzmhczabtikfymtjmscxhgxbdztcoradrxwxkpomtrnwykprgkvmjsrgkhktnfgoqwqnumfsdxwrxjdnpncjfmrnbkzqeqhiojizakxcttraqophsjdpqhemyowashyilgfobdtaeortcvwcuwooudgy", "acdwnrgqmzgbxidrnlrupfbzxevpkhiqnunuuesiqqahvtivrjwqogvrrxlegvcmzzfpnpryvnvezbbheceyxvtfajjtjhssdtnfgfclwvjxzgcjmvikwgmrxyzsruolithhwepnlxwzgfldidtggzzhmjsejizxypugpfmfqbubjwzcamasjbgdfpdmqvqegqagmocnmmufeqixvmcgtoqpwqlwnocjaxikrrmpgjpldayrpkajwjptiqypkfhpjamhcukexvtpvxhdmcueqmwekmjoluqwljqahlvyjnqgfhssuaxozcdtfzobtxsf"],
               ["aoslxpjsywijvlpuqpvvmkjyryaitwbousigaujkxjtgbatrgstojnfscxroanahylbpjlgtvjdxoaxgikmgobtekffeaneravcybeagtmvxolserzrqysgfrxwktqxenjdfazcwxtfcuxltawjuehjtrctntnlbgvqhzwwzyxjvimubmpchswnhfaeecczgpjgrhosdfwzciihznnbykoxsbxaqfqxlztkdpnmmzksutoxjxhelhhajsjxnvhltdabvnsdddgmhnhvlnboetdojybkisjkgwiibimzdyqrulddsivymywoalahccygwxlbpsrmftz", "dpnbhijbyejjxyrvvshcmewhawnuaktqbepsaeezwxinhwqythtwufkjunmdyukmrsiabxdbkcdkmnpcajlbmfdmkinisurfqokhmhqmilydnzsnfefxxdvmglpymadwilzgahyedyzanjcyxwrgyhwrclflttrumieryovmkzdkmkbnhitolzcfunhvcfubxtufygaffxolkhpwmlgjawyvqxgepczxoivoinztfybqkejluhgflbtxzhlvfsoricryjhljqkmpchusioawbujwfqbijmubiioxgtpnddvxrpuzyzaebisymjlthtyjnuigtauqll"],
               ["wmobaxjqpkxywzuiqbrtbmtivtnmjnnmeqiobaqbakwtjjzjhqksesequzzpzartlktcccuakebiqpqppcgnqcwdpttyiosklrbftemmfjjipwgkaayhdqcactruhcxsmgmyjnmclfguiizlkqrbpqcemjcuvpygmagckxqyiiznwrjovyjgmdmdnagjhxhavhvtwihynjfirebyljddspalkoejxkklnyhcqvvfmlyntxskdrumscurzboyocchhimexwmyejslcoalegdcyvdxfvhbeeiygfsdteclcrgwdoojjfdliwhfuznqyxgrfzojfqbppwcxpjnzbdwo", "ulfjbhqfbmoadbqxfspbhavwfektoycabulafntkdgouoiakcxbssiolksjqvfitilpykalehgmcsmbjghwagjohrdkwxmirqnkyzlalpnxilaurdynilzjavdngnipescxpzlfmndzvdtmbudcgfxirgttcsuzfvwfkvevgleaqantvdcifpttaewbpklqyitdpbkjpcujaqkasrsgflxdbvdykcprcazamrehgwekzedhwsqiryokfyfdyhcwwzlmhmatdlrsozpyljuvluytxhcvfyipbjiyyzdivgzqmjtjnurcgmcwnjppkbqtbkbbxuwrbxjwncwebjwoa"]
              ]
    
    time_dictionary = {}
    for lists in strings:
        start_time_d = time.time()
        lcs_dynamic(string1=lists[0], string2=lists[1], show=False)
        end_time_d = time.time()
        total_time_d = end_time_d - start_time_d

        start_time_dac = time.time()
        lcs_divide_conquer(s1=lists[0], s2=lists[1], show_dac=False)
        end_time_dac = time.time()
        total_time_dac = end_time_dac - start_time_dac

        key = str(len(lists[0]))
        time_dictionary.update({key: {'d': total_time_d, 'dac': total_time_dac}})

    x = list(time_dictionary.keys())    
    y_d = [time_dictionary[key]['d'] for key in x]
    y_dac = [time_dictionary[key]['dac'] for key in x]

    plt.plot(x, y_d, label='Dynamic')
    plt.plot(x, y_dac, label='Divide and Conquer')
    plt.xlabel('Cantidad de caracteres')
    plt.ylabel('Tiempo (s)')

    plt.legend()
    plt.show()

if __name__ == '__main__':
    time_collector()